### ISSUE TITLE
Bot no longer offers to minimize CI?

### ISSUE THREAD

**Issue by JasonGross** [coq/bot#258] opened 2022-11-24 23:43 UTC
@Zimmi48 do you know what's going on with the bot not offering to minimize https://github.com/coq/coq/pull/16904#issuecomment-1326875225 ?

**Comment by ppedrot** [comment] 2022-11-25 08:55
I don't think it used to for draft PRs, but maybe I'm misremembering?

**Comment by Zimmi48** [comment] 2022-11-25 15:16
The code seems to indicate that draft PRs are treated the same as the other ones:
https://github.com/coq/bot/blob/2764f82075fb5912ac2c2c25420373a13618772d/src/actions.ml#L1174-L1177

**Comment by JasonGross** [comment] 2022-11-25 15:23
Maybe the lite CI / full CI broke some parsing somewhere?

**Comment by Zimmi48** [comment] 2022-11-25 15:51
I think the problem is rather that we auto-cancel pipelines on the master branch when there is a new push now. The result is that most often than not, there is no base pipeline run.

**Comment by Zimmi48** [comment] 2022-11-25 16:17
We could revert that change, but it would make our queue grow larger. And I don't know if it's possible to do this only for master (cc @SkySkimmer).

**Comment by SkySkimmer** [comment] 2022-11-25 21:36
I don't know how to cancel prs but not master.

**Comment by SkySkimmer** [comment] 2022-12-09 14:11
>But really the main thing that it means is that we are really too low in terms of CI resources. Pipelines would be cancelled less often if that wasn't the case. (cc @maximedenes)

I don't think that's the main thing. Pipelines take multiple hours to complete even when there is no waiting for workers, so to get eg a non cancelled fiat-crypto on master we need those multiple hours to have no merges.

**Comment by Zimmi48** [comment] 2022-12-30 17:04
In principle, this should be fixed now that coq/coq#16970 is merged.

**Closed by Zimmi48** 2022-12-30 17:04 UTC
Labels: bug
