### ISSUE TITLE
github status shows cancelled light pipeline instead of full pipeline after "run full ci"

### ISSUE THREAD

**Issue by SkySkimmer** [coq/bot#331] opened 2024-11-28 16:24 UTC
For instance right now on https://github.com/coq/coq/pull/19874
![Screenshot_20241128_172342](https://github.com/user-attachments/assets/c06f9fb6-62bb-4031-a37e-ee6319db761e)

**Comment by Zimmi48** [comment] 2024-12-02 14:36
I guess this is a duplicate of #287.

**Closed by Zimmi48** 2024-12-02 14:36 UTC
Labels: bug
